#!/usr/bin/env python3
"""Gera a base CSV do radar comercial aço — Araçatuba e raio ~300 km."""

import csv
from pathlib import Path

DATA = "08/09/2026"
HEADERS = [
    "id",
    "empresa",
    "cnpj",
    "cidade",
    "estado",
    "distancia_km_aracatuba",
    "categoria",
    "subcategoria",
    "produto_provavel",
    "produto_secundario",
    "justificativa_produto",
    "potencial",
    "multiproduto",
    "multioportunidade",
    "consumo_estimado",
    "compra_recorrente",
    "tipo_operacao",
    "o_que_fabrica_constroi",
    "obras_atuais",
    "fornecedor_atual",
    "comprador",
    "cargo_comprador",
    "telefone",
    "whatsapp",
    "email",
    "site",
    "endereco",
    "fonte",
    "data_pesquisa",
    "ultimo_contato",
    "situacao",
    "proxima_acao",
    "necessidade_identificada",
    "classificacao_comercial",
    "motivo_prospect",
    "abordagem",
    "observacoes_comerciais",
]

# Campos alinhados com HEADERS (exceto id, preenchido depois)
LEADS = [
    # ========== CD — CORTE E DOBRA (prioridade máxima) ==========
    {
        "empresa": "Medida Exata Comércio de Ferro e Aço",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "CD",
        "subcategoria": "CD2",
        "produto_provavel": "SI 50 / CA-50 (reto, bobina, spooler) — VALIDAR NO CATÁLOGO nomenclatura SI vs CA",
        "produto_secundario": "CA-60 / AC-SI 60; Treliças; Telas/malhas; Arame recozido; Fio-máquina",
        "justificativa_produto": "FATO: site lista vergalhão CA-50/CA-60, treliças, malha pop, arame recozido e serviço de corte+dobra+armação. Consome matéria-prima de construção para transformar em ferragem armada.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Corte, dobra e armação + revenda atacado/varejo de aços construção",
        "o_que_fabrica_constroi": "Ferragens armadas, sapatas/gaiolas, estribos sob medida",
        "obras_atuais": "Não identificado (atende obras da região)",
        "fornecedor_atual": "Não identificado — Provável compra de usina ou distribuidor regional; validar",
        "comprador": "Não identificado — Provável Flávio (e-mail público flavio@medidaexata.net.br)",
        "cargo_comprador": "Provável — compras/comercial; validar",
        "telefone": "(18) 3608-8900",
        "whatsapp": "(18) 98184-0127",
        "email": "flavio@medidaexata.net.br",
        "site": "https://medidaexata.net.br/",
        "endereco": "Av. Jorge Mellem Rezek, 3104 — Rosele — Araçatuba/SP",
        "fonte": "medidaexata.net.br; Facebook Medida Exata Ferro e Aço",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar para compras: oferta CA-50/60 + treliças + telas; mapear volume mensal e fornecedor atual",
        "necessidade_identificada": "Matéria-prima contínua para corte/dobra/armação",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Única CD local com linha completa publicada; volume recorrente; porta de entrada para várias obras da cidade",
        "abordagem": "Posicionar como fornecedor de matéria-prima (não competir no varejo da obra). Abrir com CA-50 bobina/reto + arame. Perguntar bitolas e volume mensal.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO + MULTIOPORTUNIDADE. Também revende aço construção (concorrência parcial no varejo). Foco: ser o fornecedor da CD. Contato Facebook: +55 18 3608-8900 / 98184-0127.",
    },
    {
        "empresa": "Serv Aço",
        "cnpj": "Não identificado",
        "cidade": "Birigui",
        "estado": "SP",
        "distancia_km_aracatuba": "20",
        "categoria": "CD",
        "subcategoria": "CD2",
        "produto_provavel": "CA-50 / SI 50",
        "produto_secundario": "CA-60; Treliças; Telas; Arame recozido",
        "justificativa_produto": "FATO: anuncia linha completa de aços construção + corte, dobra e armação sob medida; atende construtoras e lojas.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Corte/dobra/armação + atacado/varejo",
        "o_que_fabrica_constroi": "Ferragem armada, treliças, estribos, malhas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3021-2898 / (18) 3642-0439",
        "whatsapp": "(18) 99645-5802",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Benedito de Souza Guimarães, 120 — Residencial Eurico Caetano — Birigui/SP — CEP 16206-463",
        "fonte": "listamais.com.br/Serv Aço Birigui",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visita Birigui junto com Saita; cotação CA-50/60 + treliças",
        "necessidade_identificada": "Suprimento recorrente de vergalhão e treliças",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "CD ativa a 20 km; compra recorrente; atende construtoras de Birigui",
        "abordagem": "Mesma lógica Medida Exata: matéria-prima + prazo. Comparar frete Araçatuba vs fornecedor atual.",
        "observacoes_comerciais": "Agrupar rota Araçatuba–Birigui.",
    },
    {
        "empresa": "Vivafer Ferro e Aço",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "CD",
        "subcategoria": "CD1",
        "produto_provavel": "CA-50 / SI 50",
        "produto_secundario": "Treliças; Arame; Estribos",
        "justificativa_produto": "FATO: site anuncia comércio de ferro para construções, vigas, sapatas, treliças, estribos e serviço de corte e dobra.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Comércio + corte e dobra",
        "o_que_fabrica_constroi": "Corte/dobra e fornecimento para obras",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3441-1165 / (18) 3622-7001",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://vivafer.com.br/",
        "endereco": "Araçatuba/SP (endereço completo não identificado no site)",
        "fonte": "vivafer.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar; confirmar se processa vergalhão ou só revende; volume",
        "necessidade_identificada": "Provável compra de vergalhão/treliças",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "CD/revenda local com telefone público e serviço de corte e dobra",
        "abordagem": "Descobrir se compra direto de usina; oferecer CA-50 + treliças com frete local.",
        "observacoes_comerciais": "Pode ser concorrente no varejo — classificar após 1º contato.",
    },
    {
        "empresa": "Birisoldas Aço, Corte e Dobra",
        "cnpj": "65.078.468/0001-44",
        "cidade": "Birigui",
        "estado": "SP",
        "distancia_km_aracatuba": "20",
        "categoria": "CD",
        "subcategoria": "CD1",
        "produto_provavel": "CA-50 / SI 50 — Provável — validar se atua em vergalhão ou chapa",
        "produto_secundario": "CA-60; Telas; Treliças — VALIDAR",
        "justificativa_produto": "FATO: CNAE/registro como serviço de corte e dobra de metais; CNAEs secundários incluem estruturas metálicas e atacado de materiais de construção. ATENÇÃO: confirmar se é armadura (CD) ou chapa (M11).",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Corte e dobra (tipo a confirmar)",
        "o_que_fabrica_constroi": "Serviço de corte e dobra de metais",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua João Cortelazzi, 2106 — Vila Isabel Marin — Birigui/SP — CEP 16204-030",
        "fonte": "mestregeo.com.br CNPJ 65.078.468/0001-44",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Visita/telefone: confirmar se corta vergalhão (manter CD) ou chapa (reclassificar M11)",
        "necessidade_identificada": "Validar tipo de aço processado",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Empresa de corte e dobra em Birigui com capital social R$ 400 mil — potencial se for armadura",
        "abordagem": "Pergunta aberta: 'vocês trabalham com vergalhão CA-50 ou com chapa?' Antes de ofertar.",
        "observacoes_comerciais": "Não classificar definitivamente como CD até validar. Datas de fundação em bases cadastrais inconsistentes — validar situação cadastral.",
    },
    {
        "empresa": "Lobisfer Ferro e Aço",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "R",
        "subcategoria": "R1",
        "produto_provavel": "CA-50 / SI 50 (revenda)",
        "produto_secundario": "Treliças; Arame; Chapas — Provável — validar portfólio",
        "justificativa_produto": "FATO: listada como aço para construção civil no centro de Araçatuba.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Distribuição/revenda de aço construção",
        "o_que_fabrica_constroi": "Comércio de aço para construção",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 2102-5600",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Aguapeí, 299 — Centro — Araçatuba/SP — CEP 16010-500",
        "fonte": "guiatelefone.com; zapia.digital",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Incluir na rota: mapear compra atacado e possível parceria/indicação",
        "necessidade_identificada": "N/A — concorrente de canal",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Revenda local do mesmo segmento — priorizar abordagem de atacado",
        "abordagem": "Abordar como prospect de atacado para revenda.",
        "observacoes_comerciais": "Potencial Alto (ex-concorrente de canal). Validar abordagem atacado/parceria.",
    },
    # ========== C — CONSTRUÇÃO ==========
    {
        "empresa": "TARRAF Incorporadora (obras Araçatuba)",
        "cnpj": "67.041.095/0001-62 (matriz SJRP)",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C3",
        "produto_provavel": "CA-50 / SI 50 — Provável via CD ou empreiteiro",
        "produto_secundario": "Treliças; Telas; Arame recozido",
        "justificativa_produto": "FATO: múltiplos empreendimentos em Araçatuba (DECK 330, Almaviva, Opus One, Monjardin; Brasília Square VGV ~R$ 230 mi previsto 2026). Consumo de aço de armadura é alto em estrutura — mas comprador pode ser CD/empreiteiro, não a incorporadora.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim (pipeline de obras)",
        "tipo_operacao": "Incorporação e construção de edifícios",
        "o_que_fabrica_constroi": "Residencial e mixed-use (Brasília Square)",
        "obras_atuais": "DECK 330; Brasília Square (Av. Brasília, 2090 — lançamento); outros entregues/em andamento",
        "fornecedor_atual": "Não identificado — pergunta-chave: quem fornece o aço?",
        "comprador": "Não identificado — Provável engenharia de obras / suprimentos matriz SJRP",
        "cargo_comprador": "Provável — Gerente de suprimentos / engenheiro residente; validar",
        "telefone": "(17) 4004-6655 / (17) 3354-1500",
        "whatsapp": "Não identificado",
        "email": "contato@tarraf.com.br",
        "site": "https://tarraf.com.br/",
        "endereco": "Escritório Araçatuba: Av. Brasília, 2090 — SP 16015-645 | Matriz: Av. Juscelino K. de Oliveira, 2000 — SJRP",
        "fonte": "tarraf.com.br; aracatubafacts; lr1.com.br; LinkedIn TARRAF",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visitar canteiro DECK 330 / Brasília Square: identificar placa de CD/fornecedor de aço; depois abordar CD ou suprimentos",
        "necessidade_identificada": "Armadura para estruturas de edifícios — comprador oculto a mapear",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Maior pipeline imobiliário ativo em Araçatuba; volume de aço significativo nas obras",
        "abordagem": "NÃO ofertar direto sem mapear comprador. Abordagem: engenharia da obra → 'quem está fornecendo o aço?' → atacar CD/empreiteiro.",
        "observacoes_comerciais": "⭐ MULTIOPORTUNIDADE (obra + CD oculta). Sede compras pode ser SJRP (~140 km).",
    },
    {
        "empresa": "Pacaembu Construtora (obras Araçatuba)",
        "cnpj": "96.298.013/0001-68",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C1",
        "produto_provavel": "CA-50 / SI 50 — Provável via CD ou compra centralizada",
        "produto_secundario": "Treliças; Telas; Arame",
        "justificativa_produto": "FATO: Residencial Campo Belo (771 casas, ~R$ 146 mi); Vida Nova Araçatuba Fase 3 em obras; >2.500 unidades na cidade. Casas MCMV consomem armadura de fundação/laje/cintas.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Construtora/incorporadora habitacional",
        "o_que_fabrica_constroi": "Residenciais de interesse social e casas",
        "obras_atuais": "Campo Belo (Umuarama/Pinheiros); Vida Nova Fase 3 (Rua Duque de Caxias, 330 — Centro — status Em Obras)",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado — Provável suprimentos regional (SJRP/Bauru) ou engenheiro de obra",
        "cargo_comprador": "Provável — Suprimentos / engenharia; validar",
        "telefone": "0800 730 2020 / (11) 3236-4141",
        "whatsapp": "Não identificado",
        "email": "atendimento@pacaembu.com",
        "site": "https://pacaembu.com/",
        "endereco": "Obra Vida Nova: Rua Duque de Caxias, 330 — Centro — Araçatuba/SP | Matriz Bauru/SP",
        "fonte": "pacaembu.com; Prefeitura Araçatuba; LinkedIn Pacaembu",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visitar Vida Nova Fase 3 e Campo Belo: identificar fornecedor de aço/CD; contactar engenheiro residente",
        "necessidade_identificada": "Armadura em escala para casas em série",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Maior volume habitacional ativo na cidade; consumo recorrente por fase",
        "abordagem": "Mapear comprador real (central vs obra). Oferecer kit obra: CA-50 + treliças + telas com logística de canteiro.",
        "observacoes_comerciais": "⭐ MULTIOPORTUNIDADE. Compras podem ser centralizadas fora de Araçatuba.",
    },
    {
        "empresa": "Ferreira Engenharia",
        "cnpj": "Não identificado",
        "cidade": "Penápolis",
        "estado": "SP",
        "distancia_km_aracatuba": "50",
        "categoria": "C",
        "subcategoria": "C1",
        "produto_provavel": "CA-50 / SI 50 — Provável — validar se compra direto",
        "produto_secundario": "Treliças; Telas; Telha/coberturas em obras comerciais — Provável",
        "justificativa_produto": "FATO: construtora/incorporadora com obras em Araçatuba (Ferreira Hub, Central Park Tower/Aya) e Penápolis (Ferreira Liv); >100 obras no histórico.",
        "potencial": "Alto",
        "multiproduto": "Provável — validar",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Incorporação, construção e desenvolvimento urbano",
        "o_que_fabrica_constroi": "Residencial, comercial, shopping, hub multiuso",
        "obras_atuais": "Ferreira Hub e empreendimentos em Araçatuba; Ferreira Liv em Penápolis",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — suprimentos; validar",
        "telefone": "(18) 3654-2030",
        "whatsapp": "Não identificado",
        "email": "contato@ferreiraengenharia.com.br",
        "site": "https://ferreiraengenharia.com.br/",
        "endereco": "Rua Vitor Antonio Janjácomo, 673 — Penápolis/SP — CEP 16306-522",
        "fonte": "ferreiraengenharia.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "E-mail/telefone comercial + visita canteiro Hub Araçatuba",
        "necessidade_identificada": "Aço de armadura e possivelmente coberturas/estruturas",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Construtora regional com obras ativas em Araçatuba e sede a 50 km",
        "abordagem": "Agendar com engenharia de obras; perguntar política de compra de aço (CD vs direto).",
        "observacoes_comerciais": "Sede Penápolis — combinar rota com outras visitas.",
    },
    {
        "empresa": "QCON Construtora e Incorporadora",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C3",
        "produto_provavel": "CA-50 / SI 50 — Provável — validar",
        "produto_secundario": "Treliças; Telas",
        "justificativa_produto": "FATO: construtora/incorporadora local com projetos residenciais e comerciais em Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Construção e incorporação",
        "o_que_fabrica_constroi": "Projetos residenciais, comerciais e de investimento",
        "obras_atuais": "Não identificado no site — validar obras ativas",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(14) 99832-0640",
        "whatsapp": "(14) 99832-0640",
        "email": "comercial@construtoraqcon.com.br",
        "site": "https://construtoraqcon.com.br/",
        "endereco": "Av. Brasília, 2121 — Araçatuba/SP",
        "fonte": "construtoraqcon.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp comercial: perguntar obras em andamento e quem compra aço",
        "necessidade_identificada": "Armadura conforme pipeline de obras",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Incorporadora local acessível; potencial médio se houver obra ativa",
        "abordagem": "Contato direto WhatsApp; qualificar obra e estágio estrutural.",
        "observacoes_comerciais": "DDD 14 no telefone — confirmar se comercial atende Araçatuba.",
    },
    {
        "empresa": "Yama Engenharia",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C4",
        "produto_provavel": "CA-50 / SI 50 — Provável — validar",
        "produto_secundario": "Treliças; Arame",
        "justificativa_produto": "FATO: gestão/construção de residências de alto padrão em Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Engenharia / gestão de obras residenciais",
        "o_que_fabrica_constroi": "Residências de alto padrão",
        "obras_atuais": "Não identificado (portfólio genérico no site)",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3625-1300",
        "whatsapp": "Não identificado",
        "email": "administrativo@yamaengenharia.com.br",
        "site": "https://yamaengenharia.com.br/",
        "endereco": "R. Carlos Gomes, 239 — 5º andar, Sala 501 — Centro — Araçatuba/SP — CEP 16010-310",
        "fonte": "yamaengenharia.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Ligar: confirmar se compra aço ou só gerencia; obras ativas",
        "necessidade_identificada": "Possível indicação de CD/fornecedor da obra",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Obras residenciais alto padrão consomem aço; pode ser porta de indicação",
        "abordagem": "Qualificar se compra ou indica. Volume unitário menor que Pacaembu/TARRAF.",
        "observacoes_comerciais": "Pode ser tratado como parceiro/indicação se não comprar direto.",
    },
    {
        "empresa": "Obra — Residencial Campo Belo (Pacaembu)",
        "cnpj": "N/A — obra",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C4",
        "produto_provavel": "CA-50; Treliças; Telas",
        "produto_secundario": "Arame recozido",
        "justificativa_produto": "FATO: 771 casas MCMV, investimento ~R$ 146 mi; fundações e lajes consomem armadura em série.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim (durante obra)",
        "tipo_operacao": "Canteiro habitacional",
        "o_que_fabrica_constroi": "771 casas",
        "obras_atuais": "Campo Belo — entre Umuarama e Pinheiros",
        "fornecedor_atual": "Não identificado — investigar no canteiro",
        "comprador": "Não identificado — engenheiro/mestre ou CD fornecedora",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado (via Pacaembu)",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://www.aracatuba.sp.gov.br/noticias/araatuba-recebe-novo-residencial-com-771-casas-e-investimento-de-rs-146-milhes",
        "endereco": "Área entre bairros Umuarama e Pinheiros — Araçatuba/SP",
        "fonte": "Prefeitura Municipal de Araçatuba",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visita presencial ao canteiro: fotografar placas de fornecedores; falar com mestre de obras",
        "necessidade_identificada": "Quem está fornecendo o aço dessa obra?",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Obra de alto volume — cliente oculto (CD) pode ser mais valioso que a construtora",
        "abordagem": "Investigação de canteiro, não pitch de catálogo.",
        "observacoes_comerciais": "Registro de obra para inteligência comercial; vincular a Pacaembu + CD descoberta.",
    },
    {
        "empresa": "Obra — Brasília Square by Tarraf",
        "cnpj": "N/A — obra",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C11",
        "produto_provavel": "CA-50; Treliças; Telas",
        "produto_secundario": "Possível telha/fechamentos em fases posteriores — Provável — validar",
        "justificativa_produto": "FATO: mixed-use VGV ~R$ 230 mi; studios + salas comerciais; estrutura de edifício exige armadura significativa.",
        "potencial": "Alto",
        "multiproduto": "Provável — validar",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim (durante obra)",
        "tipo_operacao": "Canteiro mixed-use",
        "o_que_fabrica_constroi": "Studios, salas comerciais, uso misto",
        "obras_atuais": "Brasília Square — Av. Brasília, 2090 — Jardim Nova Yorque (lançamento/previsão 2026)",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Via TARRAF (17) 4004-6655",
        "whatsapp": "Não identificado",
        "email": "contato@tarraf.com.br",
        "site": "https://tarraf.com.br/",
        "endereco": "Avenida Brasília, 2090 — Jardim Nova Yorque — Araçatuba/SP",
        "fonte": "lr1.com.br; aracatubafacts.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Monitorar início de estrutura; visitar canteiro quando houver armação",
        "necessidade_identificada": "Fornecedor de aço da obra (a descobrir)",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Maior lançamento TARRAF na cidade; timing de compra de aço a acompanhar",
        "abordagem": "Acompanhar estágio; atacar na fase de fundação/estrutura.",
        "observacoes_comerciais": "Pode ainda estar em fase pré-obra; validar status real no local.",
    },
    {
        "empresa": "Obra — Vida Nova Araçatuba Fase 3 (Pacaembu)",
        "cnpj": "N/A — obra",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C4",
        "produto_provavel": "CA-50; Treliças",
        "produto_secundario": "Telas; Arame",
        "justificativa_produto": "FATO: status 'Em Obras' no site Pacaembu; casas de interesse social.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Canteiro habitacional",
        "o_que_fabrica_constroi": "Casas interesse social — Fase 3",
        "obras_atuais": "Em Obras — Vida Nova Araçatuba 3",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Via Pacaembu 0800 730 2020",
        "whatsapp": "Não identificado",
        "email": "atendimento@pacaembu.com",
        "site": "https://pacaembu.com/imoveis-residenciais/vida-nova-aracatuba-fase-3",
        "endereco": "Rua Duque de Caxias, nº 330 — Centro — Araçatuba/SP",
        "fonte": "pacaembu.com",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visita canteiro esta semana — mapear fornecedor de aço",
        "necessidade_identificada": "Armadura em andamento",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Obra já em execução = consumo atual, não futuro",
        "abordagem": "Canteiro primeiro; depois CD/suprimentos.",
        "observacoes_comerciais": "Melhor timing entre as obras Pacaembu (já em obras).",
    },
    # ========== M — METALÚRGICA / TRANSFORMAÇÃO ==========
    {
        "empresa": "ZBN Indústria Mecânica",
        "cnpj": "64.822.810/0001-06 (e filiais)",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M1",
        "produto_provavel": "Chapa quente; Bobina laminada a quente",
        "produto_secundario": "Chapa inox / Bobina inox 304; Barras; Perfis",
        "justificativa_produto": "FATO: caldeiraria pesada + fundição + oxicorte CNC em chapas de grande porte; trabalha aço carbono e inox; parque 20.000 m²; pontes >50 t. Fluxo: chapa/bobina → oxicorte/caldeiraria → equipamentos industriais.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Fundição, usinagem, caldeiraria, montagem industrial",
        "o_que_fabrica_constroi": "Peças e equipamentos para sucroalcooleiro, mineração, alimentício, químico, energia",
        "obras_atuais": "N/A — produção contínua sob encomenda",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — compras industriais / PCP; validar",
        "telefone": "Não identificado no site (formulário)",
        "whatsapp": "Não identificado",
        "email": "Não identificado no site",
        "site": "https://pcp.zbn.com.br/",
        "endereco": "Rua Prof. Rubens Rego Fontão, 372/392 — Parque Industrial — CEP 16075-245 — Araçatuba/SP",
        "fonte": "pcp.zbn.com.br; mapaindustrial.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visita presencial à fábrica; falar com compras: espessuras de chapa carbono e inox",
        "necessidade_identificada": "Chapas carbono grossas + inox para caldeiraria",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Maior transformador metal-mecânico local identificado; multiproduto; consumo recorrente",
        "abordagem": "Abrir com chapa quente/oxicorte (necessidade óbvia). Segundo passo: inox 304. Levar tabela de espessuras.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO + MULTIOPORTUNIDADE (M + I). Capital social ~R$ 6,7 mi nas bases. Alvo âncora do funil M.",
    },
    {
        "empresa": "Passador & Cia Ltda.",
        "cnpj": "Não identificado",
        "cidade": "Andradina",
        "estado": "SP",
        "distancia_km_aracatuba": "100",
        "categoria": "M",
        "subcategoria": "M1",
        "produto_provavel": "Chapa quente; Bobina laminada a quente",
        "produto_secundario": "Chapa inox 304/316; Tubo industrial; Galvanizado (quando aplicável)",
        "justificativa_produto": "FATO: caldeiraria pesada 50+ anos; plasma/oxicorte/laser; dobra; solda carbono/inox/alumínio; tanques; tubulações; galvanização a fogo própria; atende usinas. Fluxo: chapa → corte/dobra/caldeiraria → tanques/estruturas/tubulações.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Caldeiraria pesada industrial",
        "o_que_fabrica_constroi": "Tanques, dutos, estruturas, tubulações, steel deck, insertos, guarda-corpo",
        "obras_atuais": "Atende usinas (incl. região Andradina/Raízen)",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — compras; validar",
        "telefone": "(18) 3722-3636",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://passador.ind.br/",
        "endereco": "Av. Guanabara, 2419 — Stella Maris — Andradina/SP — CEP 16901-100",
        "fonte": "passador.ind.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar + visita Andradina combinada com JBS/Raízen Gasa",
        "necessidade_identificada": "Chapas carbono e inox para caldeiraria e usinas",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Grande transformador com multiproduto e vínculo com sucroalcooleiro",
        "abordagem": "Foco chapa quente espessas + inox. Mencionar capacidade de fornecimento para projetos de usina.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO. Distância ~100 km — justificar com volume.",
    },
    {
        "empresa": "Megatec Implementos Agrícolas",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M14",
        "produto_provavel": "Chapa quente; Chapa fria",
        "produto_secundario": "Tubo industrial; Metalon; Perfis U; Barra chata; Bobina",
        "justificativa_produto": "FATO: fabrica implementos agrícolas (transbordos, carrocerias canavieiras) com verticalização interna da estrutura. Fluxo: chapa/tubo/perfil → soldagem/estrutura → implemento.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Fabricação de implementos agrícolas",
        "o_que_fabrica_constroi": "Transbordos, implementos sucroalcooleiros e para grãos",
        "obras_atuais": "N/A — linha de produção",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — compras; validar",
        "telefone": "(18) 2103-2021",
        "whatsapp": "Não identificado",
        "email": "contato@megatecindustria.com.br / atendimento@megatecindustria.com.br",
        "site": "https://www.megatecindustria.com.br/",
        "endereco": "Rodovia Marechal Rondon, KM 527 — Araçatuba/SP — CEP 16018-805",
        "fonte": "megatecindustria.com.br; LinkedIn megatec.industria",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "E-mail + visita: mapear espessuras de chapa e bitolas de tubo/metalon",
        "necessidade_identificada": "Aço estrutural contínuo para implementos",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Transformador verticalizado; vários grupos do catálogo; recorrência industrial",
        "abordagem": "Abrir com chapa + metalon/tubo (kit implemento). Oferecer programação de fornecimento.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO. Vizinha da Nestlé na Rondon — rota industrial.",
    },
    {
        "empresa": "Estruturas Metálicas Saita",
        "cnpj": "48.431.803/0001-27",
        "cidade": "Birigui",
        "estado": "SP",
        "distancia_km_aracatuba": "20",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Perfis U; Metalon; Tubo industrial",
        "produto_secundario": "Chapa quente; Telha trapezoidal/ondulada; Cantoneiras; Barra chata",
        "justificativa_produto": "FATO: fabricação própria de estruturas metálicas desde 1979; galpões industriais e agrícolas; montagem completa. Fluxo: perfil/tubo/chapa → estrutura → galpão.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Fabricação e montagem de estruturas metálicas",
        "o_que_fabrica_constroi": "Galpões industriais, comerciais, armazéns agrícolas",
        "obras_atuais": "Não identificado (produção sob demanda)",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3642-3611",
        "whatsapp": "(18) 99639-7794",
        "email": "Não identificado",
        "site": "https://estruturametalicasaita.com.br/",
        "endereco": "Rua Dr. Luiz de T. P. Sobrinho, 382 — Resid. Alvorada — Birigui/SP — CEP 16204-296",
        "fonte": "estruturametalicasaita.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp: oferta perfis + metalon + telhas; visita com Serv Aço no mesmo dia",
        "necessidade_identificada": "Perfis estruturais e coberturas para galpões",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante de estruturas com 45+ anos; consumo de múltiplas linhas",
        "abordagem": "Kit galpão: perfis U + metalon + telha trapezoidal/cumeeiras.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO. Excelente aderência a coberturas do catálogo.",
    },
    {
        "empresa": "André Ferro e Aço",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "R",
        "subcategoria": "R5",
        "produto_provavel": "Bobina / Chapa (para revenda e corte)",
        "produto_secundario": "Tubos; Metalon; Perfis U; Barras; Cantoneiras",
        "justificativa_produto": "FATO: distribui ferro e aço desde 2015; corte a laser, oxicorte, corte e dobra de chapas; vende chapas 1,20–100 mm, tubos, laminados, perfis. NÃO listou vergalhão CA — classificar como centro de serviço/distribuição, não CD de armadura.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Distribuição + centro de serviço (corte laser/oxicorte/dobra de chapa)",
        "o_que_fabrica_constroi": "Corta/dobra chapas; revende tubos, perfis, laminados",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3623-1770",
        "whatsapp": "(18) 3623-1770",
        "email": "vendas@andreferroeaco.com.br",
        "site": "https://andreferroeaco.com.br/",
        "endereco": "Rua Dr. Francisco Vilela, 825 — Umuarama — Araçatuba/SP — CEP 16013-240",
        "fonte": "andreferroeaco.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Avaliar se há linha em que possam comprar (atacado) sem conflito; senão manter fora da rota",
        "necessidade_identificada": "Compra de bobina/chapa para revenda — possível cliente atacado",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Portfólio sobreposto (chapas, tubos, perfis, barras) + serviço de corte",
        "abordagem": "Abordar com foco em venda atacado para centro de serviço.",
        "observacoes_comerciais": "Pode gerar indicação de clientes finais. Não confundir corte de chapa com CD de vergalhão.",
    },
    {
        "empresa": "Serralheria 5 Estrelas",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M6",
        "produto_provavel": "Perfis / Barras / Kits para portas de enrolar — VALIDAR NO CATÁLOGO itens exatos",
        "produto_secundario": "Metalon; Tubo 5\"; Chapa; Barra chata",
        "justificativa_produto": "FATO: desde 1994 fabrica portas de enrolar automáticas/manuais, portões basculantes e estruturas. Fluxo: perfil/barra/chapa → porta/portão.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Serralheria industrial/comercial — portas e portões",
        "o_que_fabrica_constroi": "Portas de enrolar, portões, escadas, grades, estruturas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 99746-6694",
        "whatsapp": "(18) 99746-6694",
        "email": "Não identificado (site tem formulário)",
        "site": "https://www.serralheria5estrelas.com.br/",
        "endereco": "Av. Odorindo Perenha, 892 — Umuarama — Araçatuba/SP — CEP 16013-230",
        "fonte": "serralheria5estrelas.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp: ofertar linha portas de enrolar (perfis, barras, kits, tubo 5\")",
        "necessidade_identificada": "Matéria-prima para portas de enrolar e portões",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Aderência direta à linha Portas de Enrolar do catálogo",
        "abordagem": "Abrir com kit porta de enrolar. Segundo produto: metalon para portões.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO na linha de portas/portões. Vizinha da Estruturas Metálicas Araçatuba.",
    },
    {
        "empresa": "Fenasi Indústria e Comércio de Artefatos de Aço",
        "cnpj": "51.093.318/0001-03",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis U; Tubo industrial",
        "produto_secundario": "Chapa; Telha; Cantoneiras",
        "justificativa_produto": "FATO: desde 1977/1979 fabrica estruturas metálicas, mezaninos, portões; CNAE serralheria e montagem de estruturas.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Estruturas metálicas e serralheria",
        "o_que_fabrica_constroi": "Estruturas, mezaninos, portões, coberturas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3623-4692",
        "whatsapp": "Não identificado",
        "email": "emodelo@ig.com.br",
        "site": "Não identificado",
        "endereco": "Rua América do Sul, 1077 — Jardim Brasília — Araçatuba/SP — CEP 16025-600",
        "fonte": "listamais.com.br; diariocidade.com; guiadocnpj",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar: volume mensal de metalon/perfis",
        "necessidade_identificada": "Aço para estruturas e serralheria",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Transformador estabelecido há décadas; consumo de perfis/tubos",
        "abordagem": "Oferta metalon + perfis U + chapa.",
        "observacoes_comerciais": "E-mail parece antigo — preferir telefone.",
    },
    {
        "empresa": "Estruturas Metálicas Araçatuba",
        "cnpj": "12.671.264/0001-56",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis U; Tubo",
        "produto_secundario": "Chapa; Cantoneiras",
        "justificativa_produto": "FATO: CNAE fabricação de estruturas metálicas; EPP ativa.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Fabricação de estruturas metálicas",
        "o_que_fabrica_constroi": "Estruturas metálicas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado (sócios públicos: Rogerio Augusto Massarente; Gabriely Guimaraes Pedroso)",
        "cargo_comprador": "Provável — sócio/compras; validar",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Av. Odorindo Perenha, 880 — Umuarama — Araçatuba/SP — CEP 16013-230",
        "fonte": "mestregeo.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Buscar telefone no Maps e visitar (mesma rua da 5 Estrelas)",
        "necessidade_identificada": "Provável metalon/perfis",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante local de estruturas; endereço no polo Umuarama",
        "abordagem": "Visita a frio no cluster Umuarama (Odorindo Perenha).",
        "observacoes_comerciais": "Porte pequeno/EPP — potencial Médio.",
    },
    {
        "empresa": "Pratesfer Estruturas Metálicas e Serralheria",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M5",
        "produto_provavel": "Metalon; Tubo; Chapa",
        "produto_secundario": "Perfis; Barras",
        "justificativa_produto": "FATO: listada como estruturas metálicas e serralheria em Araçatuba.",
        "potencial": "Baixo",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Serralheria / estruturas",
        "o_que_fabrica_constroi": "Estruturas e serviços de serralheria",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3301-6191",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Joaquim Murtinho, 55 — São Joaquim / Vila Estádio — Araçatuba/SP",
        "fonte": "serralherias.net",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Ligar apenas após esgotar leads A",
        "necessidade_identificada": "Provável metalon/chapa em baixo volume",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Serralheria local — volume provavelmente baixo",
        "abordagem": "Qualificar volume antes de visitar.",
        "observacoes_comerciais": "Prioridade C.",
    },
    {
        "empresa": "Noroagro Truck Center",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M14",
        "produto_provavel": "Chapa; Tubo; Metalon — Provável — validar",
        "produto_secundario": "Barra chata; Perfis",
        "justificativa_produto": "FATO: manutenção/reforma/adaptação de implementos agrícolas e industriais; alongamento de chassi; reformas de baú/canavieira/transbordo. Consome aço em reformas (menor que fabricante OEM).",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Reforma e adaptação de implementos",
        "o_que_fabrica_constroi": "Reformas de implementos agrícolas/rodoviários",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3623-9049",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://noroagro.com.br/",
        "endereco": "Araçatuba/SP (matriz); filiais Andradina, Lins, Barra do Garças",
        "fonte": "noroagro.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar: mapear compra de chapa/tubo para reformas",
        "necessidade_identificada": "Aço para reformas de implementos",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Consumo recorrente em reformas; rede regional",
        "abordagem": "Oferta chapa + tubo com entrega rápida (urgencia de oficina).",
        "observacoes_comerciais": "Volume tende a ser menor que Megatec (OEM).",
    },
    # ========== I — INDÚSTRIA / INOX ==========
    {
        "empresa": "Ata Inox / Atainox",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I4",
        "produto_provavel": "Chapa inox 304; Bobina inox",
        "produto_secundario": "Inox 430; Acabamentos 2B/N4; Tiras; Blanks; Filmes",
        "justificativa_produto": "FATO: fabrica equipamentos e peças em aço inox para frigoríficos, restaurantes, supermercados. Fluxo: chapa/bobina inox → equipamento. Liga típica alimentícia: 304 (Provável — validar).",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Fabricação de equipamentos em inox",
        "o_que_fabrica_constroi": "Equipamentos e peças de aço inox",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3625-8730 / (18) 99736-1893",
        "whatsapp": "(18) 99736-1893",
        "email": "atainox@atainox.com / ccontato@atainox.com",
        "site": "https://atainox.com/",
        "endereco": "Rua América do Sul, 1022 — Jardim Brasília — Araçatuba/SP — CEP 16025-600",
        "fonte": "atainox.com; listagens locais",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp: perguntar ligas (304/430), espessuras e formato (chapa/bobina/blank)",
        "necessidade_identificada": "Inox para fabricação de equipamentos",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Comprador direto de inox com transformação; aderência total ao catálogo inox",
        "abordagem": "Abrir com 304 2B + filme. Segundo: 430 e N4 escovado. Levar amostras de acabamento se possível.",
        "observacoes_comerciais": "⭐ MULTIPRODUTO (linhas inox). Alvo âncora do funil I.",
    },
    {
        "empresa": "AISI Indústria e Comércio de Equipamentos em Aço Inox",
        "cnpj": "32.914.253/0001-67",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I4",
        "produto_provavel": "Chapa inox 304",
        "produto_secundario": "Inox 430; Tiras; Blanks",
        "justificativa_produto": "FATO: razão social e CNAEs de usinagem/solda e esquadrias; foco equipamentos em aço inox.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Usinagem, solda e equipamentos inox",
        "o_que_fabrica_constroi": "Equipamentos e serviços em aço inox",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Vila Industrial — Araçatuba/SP — CEP 16072-100",
        "fonte": "databrasil.net CNPJ 32.914.253/0001-67",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Localizar telefone Maps; visitar cluster Vila Industrial com Inox e Cia",
        "necessidade_identificada": "Inox para fabricação/solda",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante local de equipamentos inox",
        "abordagem": "Qualificar ligas e consumo mensal.",
        "observacoes_comerciais": "Fundada 2019 — porte a validar.",
    },
    {
        "empresa": "Inox e Cia Equipamentos e Serviços",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I4",
        "produto_provavel": "Chapa inox 304 — Provável — validar",
        "produto_secundario": "430; Filmes; Acabamentos",
        "justificativa_produto": "FATO: listada como aço inoxidável / equipamentos e serviços; avaliações de peças e acabamento.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Equipamentos e serviços em inox",
        "o_que_fabrica_constroi": "Peças/equipamentos em inox",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Provável — Maurício (citado em avaliação pública)",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3625-9720",
        "whatsapp": "(18) 99623-0210",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Manoel Antônio Monteiro, 48 — Vila Industrial — Araçatuba/SP — CEP 16072-100",
        "fonte": "listamais.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp: oferta 304 2B",
        "necessidade_identificada": "Inox para serviços/equipamentos",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Consumidor local de inox com contato WhatsApp",
        "abordagem": "Amostra/preço 304; perguntar espessuras mais usadas.",
        "observacoes_comerciais": "Volume provavelmente menor que Ata Inox.",
    },
    {
        "empresa": "Brazzatti Inox",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I4",
        "produto_provavel": "Chapa inox 304 — Provável — validar",
        "produto_secundario": "430; N4",
        "justificativa_produto": "FATO: listada como aço inoxidável; avaliações mencionam peças produzidas.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Produção de peças em inox",
        "o_que_fabrica_constroi": "Peças em inox",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 99787-3677",
        "whatsapp": "(18) 99787-3677",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Canjiro Takebe, 383 — Palmeiras — Araçatuba/SP — CEP 16071-205",
        "fonte": "listamais.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "WhatsApp curto: ligas e espessuras",
        "necessidade_identificada": "Inox para peças",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante local de peças inox",
        "abordagem": "Qualificar consumo antes de visita.",
        "observacoes_comerciais": "Lead B/C conforme volume.",
    },
    {
        "empresa": "Metalúrgica Plasminox",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I5",
        "produto_provavel": "Chapa inox 304",
        "produto_secundario": "Bobina; Tiras",
        "justificativa_produto": "FATO: metalúrgica listada em aço inoxidável — nome indica especialização inox.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Metalúrgica inox",
        "o_que_fabrica_constroi": "Produtos/serviços em inox (detalhe a validar)",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 3608-3008",
        "whatsapp": "(18) 99726-4764",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Clibas de Almeida Prado, 1710 — Presidente — Araçatuba/SP — CEP 16072-605",
        "fonte": "listamais.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Ligar: confirmar processos e consumo",
        "necessidade_identificada": "Inox para metalurgia",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Metalúrgica especializada em inox",
        "abordagem": "Mapear ligas e formatos.",
        "observacoes_comerciais": "",
    },
    {
        "empresa": "Aquinox Indústria e Comércio",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I4",
        "produto_provavel": "Chapa inox — Provável — validar",
        "produto_secundario": "304; 430",
        "justificativa_produto": "FATO: listada no Parque Industrial como aço inoxidável.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Indústria/comércio inox",
        "o_que_fabrica_constroi": "Não detalhado publicamente",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "(18) 98153-4682",
        "whatsapp": "(18) 98153-4682",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Brigadeiro Faria Lima, 7671 — Parque Industrial Maria Isabel — Araçatuba/SP — CEP 16080-751",
        "fonte": "listamais.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "WhatsApp: qualificar se fabrica ou só comercializa",
        "necessidade_identificada": "Validar se compra inox para transformar ou revende",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Nome/listagem inox no parque industrial — precisa qualificação",
        "abordagem": "Descobrir se é fabricante (I) ou revenda (R2/concorrente).",
        "observacoes_comerciais": "Se for só revenda de inox, qualificar como prospect de canal/atacado.",
    },
    {
        "empresa": "Nestlé Brasil — Unidade Araçatuba",
        "cnpj": "60.409.075/0029-53",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I3",
        "produto_provavel": "Chapa inox 304 — Provável para manutenção/ampliação — validar",
        "produto_secundario": "Tubulações industriais via caldeiraria contratada; 316 se processo exigir — VALIDAR",
        "justificativa_produto": "FATO: fábrica de laticínios (CNAE 1052-0/00) na Rondon Km 531. Processos lácteos exigem superfícies sanitárias em inox. Compra pode ser: (a) MRO via compras corporativas; (b) via caldeirarias contratadas (ZBN etc.).",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Provável — validar (paradas/manutenção)",
        "tipo_operacao": "Indústria de laticínios",
        "o_que_fabrica_constroi": "Produtos lácteos",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado — Provável via contratadas de manutenção",
        "comprador": "Não identificado — Provável compras industriais / facilities",
        "cargo_comprador": "Provável — Suprimentos MRO; validar",
        "telefone": "(18) 3631-6111 / (11) 5508-4400",
        "whatsapp": "Não identificado",
        "email": "Não identificado (unidade)",
        "site": "Não identificado (corporativo nestle.com.br)",
        "endereco": "Rodovia Marechal Rondon, KM 531 — Iporã — Araçatuba/SP — CEP 16021-900",
        "fonte": "Receita/CNPJ bases; Cliquei Achei; ruacep",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Mapear via ZBN/caldeirarias quem atende a Nestlé; LinkedIn compras da unidade",
        "necessidade_identificada": "Inox sanitário — canal de compra a descobrir",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Grande indústria alimentícia local com justificativa clara de inox",
        "abordagem": "Difícil acesso direto. Estratégia: (1) fornecedor de caldeiraria que atende a planta; (2) cadastro de fornecedores MRO.",
        "observacoes_comerciais": "⭐ MULTIOPORTUNIDADE (I + caldeirarias). Não presumir compra direta de bobina.",
    },
    {
        "empresa": "JBS — Unidade Andradina",
        "cnpj": "Não identificado (unidade)",
        "cidade": "Andradina",
        "estado": "SP",
        "distancia_km_aracatuba": "100",
        "categoria": "I",
        "subcategoria": "I2",
        "produto_provavel": "Chapa inox 304 — Provável via manutenção/projetos — validar",
        "produto_secundario": "Equipamentos via fabricantes inox; tubulações",
        "justificativa_produto": "FATO: frigorífico exportador habilitado (ex.: Indonésia); ambiente de proteína animal exige inox sanitário. Compra tipicamente corporativa ou via contratadas.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Frigorífico / abate bovino",
        "o_que_fabrica_constroi": "Processamento de carne bovina",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado — Provável compras JBS corporativo ou manutenção local",
        "cargo_comprador": "Provável — Manutenção / Suprimentos; validar",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://www.jbs.com.br/",
        "endereco": "Andradina/SP (unidade frigorífica)",
        "fonte": "andravirtual.com.br; IEA-SP histórico regional",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Rota Andradina: Passador + JBS — mapear contratadas de caldeiraria inox",
        "necessidade_identificada": "Inox para planta frigorífica",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Grande consumidor potencial de inox sanitário na região",
        "abordagem": "Indireta via Passador/Ata Inox que atendem frigoríficos; ou portal de fornecedores JBS.",
        "observacoes_comerciais": "Acesso difícil; alto potencial se entrar na cadeia de manutenção.",
    },
    {
        "empresa": "Raízen — Filial GASA (Andradina)",
        "cnpj": "Não identificado (filial)",
        "cidade": "Andradina",
        "estado": "SP",
        "distancia_km_aracatuba": "100",
        "categoria": "I",
        "subcategoria": "I12",
        "produto_provavel": "Chapa quente / estruturas — Provável via contratadas — validar",
        "produto_secundario": "Inox para processos; Tubos; Perfis",
        "justificativa_produto": "FATO: usina sucroalcooleira Raízen Gasa em Andradina; projetos E2G/ampliações históricos. Manutenção e projetos consomem aço carbono e inox, geralmente via caldeirarias (ex.: Passador).",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim (safra/manutenção)",
        "tipo_operacao": "Usina de açúcar e etanol",
        "o_que_fabrica_constroi": "Açúcar, etanol (incl. projetos E2G)",
        "obras_atuais": "Histórico de investimentos E2G — validar status atual",
        "fornecedor_atual": "Não identificado — Provável caldeirarias locais",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — Suprimentos usina / projetos; validar",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://www.raizen.com.br/",
        "endereco": "Andradina/SP — Usina Gasa",
        "fonte": "SMA/SP lista usinas; Gazeta da Região (E2G)",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Entrar via Passador/ZBN (fornecedores da usina) ou cadastro Raízen",
        "necessidade_identificada": "Aço para manutenção e projetos industriais",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Âncora sucroalcooleira regional; puxa demanda de caldeirarias",
        "abordagem": "Estratégia indireta: virar fornecedor das caldeirarias que atendem a usina.",
        "observacoes_comerciais": "⭐ MULTIOPORTUNIDADE. Cliente oculto = caldeiraria.",
    },
    {
        "empresa": "Raízen — Filial Destivale (Araçatuba)",
        "cnpj": "Não identificado (filial)",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I12",
        "produto_provavel": "Chapa / estruturas via contratadas — Provável — validar",
        "produto_secundario": "Inox; Tubos",
        "justificativa_produto": "FATO: listada em cadastros públicos de usinas CFA como Raízen Filial Destivale Araçatuba.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Usina sucroalcooleira",
        "o_que_fabrica_constroi": "Açúcar/etanol",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "https://www.raizen.com.br/",
        "endereco": "Araçatuba/SP — Filial Destivale",
        "fonte": "Lista usinas CFA jun/2022 (SMA/SP)",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Confirmar endereço/operação atual; mapear contratadas via ZBN",
        "necessidade_identificada": "Manutenção industrial",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Usina local — demanda puxada por caldeirarias",
        "abordagem": "Indireta via ZBN/Megatec/Passador.",
        "observacoes_comerciais": "Validar se unidade segue ativa sob mesmo nome.",
    },
    {
        "empresa": "Figueira Indústria e Comércio — Unidade Alcoazul",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I12",
        "produto_provavel": "Chapa / estruturas via contratadas — Provável — validar",
        "produto_secundario": "Inox",
        "justificativa_produto": "FATO: listada em cadastro público de usinas como Figueira — Unidade Alcoazul Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Usina/álcool",
        "o_que_fabrica_constroi": "Álcool/açúcar — validar operação atual",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "Lista usinas CFA jun/2022 (SMA/SP)",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Não pesquisado",
        "proxima_acao": "Validar se unidade está ativa em 2026",
        "necessidade_identificada": "Validar",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Usina histórica na lista pública — confirmar operação",
        "abordagem": "Só após confirmar atividade.",
        "observacoes_comerciais": "Lead não plenamente qualificado até validar operação.",
    },
    {
        "empresa": "Frigorífico Better Beef",
        "cnpj": "05.826.986/0017-34 (filial listada)",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I2",
        "produto_provavel": "Chapa inox 304 — Provável — validar",
        "produto_secundario": "Equipamentos via fabricantes inox",
        "justificativa_produto": "FATO: frigorífico listado em bases industriais de Araçatuba — ambiente de proteína exige inox.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Frigorífico",
        "o_que_fabrica_constroi": "Processamento de carne",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP (Parque Industrial — validar endereço)",
        "fonte": "mapaindustrial.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Confirmar se unidade opera; telefone; canal de manutenção",
        "necessidade_identificada": "Inox sanitário se planta ativa",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Frigorífico local — justificativa de inox se ativo",
        "abordagem": "Validar operação antes de ofertar.",
        "observacoes_comerciais": "Histórico regional de frigoríficos com aberturas/fechamentos — validar.",
    },
    # ========== R — DISTRIBUIÇÃO (classificação cuidadosa) ==========
    {
        "empresa": "Rodriaco Indústria e Comércio de Ferro e Aço",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "R",
        "subcategoria": "R1",
        "produto_provavel": "Linha construção/chapas — Provável portfólio concorrente",
        "produto_secundario": "Não identificado",
        "justificativa_produto": "FATO: listada como indústria e comércio de ferro e aço.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Comércio/indústria de ferro e aço",
        "o_que_fabrica_constroi": "Distribuição de aço",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Rua Brigadeiro Faria Lima, 7787 — Araçatuba/SP",
        "fonte": "infoisinfo-br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Mapear portfólio; não priorizar vendas",
        "necessidade_identificada": "N/A",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Distribuidor local — conflito de canal",
        "abordagem": "Abordar como prospect (atacado/share of wallet).",
        "observacoes_comerciais": "Mesmo eixo da Aquinox na Faria Lima.",
    },
    # ========== Complemento M / C / CD ==========
    {
        "empresa": "IMF — Indústria Metalúrgica Fabrão",
        "cnpj": "72.845.076/0001-29",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M15",
        "produto_provavel": "Chapa; Bobina — Provável — validar processo",
        "produto_secundario": "Tubo; Barras; Metalon — Provável — validar",
        "justificativa_produto": "FATO: metalúrgica listada entre as maiores indústrias locais (capital social ~R$ 11 mi). Transformação metalúrgica implica compra de aço — tipo exato a validar.",
        "potencial": "Alto",
        "multiproduto": "Provável — validar",
        "multioportunidade": "Não",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Indústria metalúrgica",
        "o_que_fabrica_constroi": "Produtos metalúrgicos (detalhe a mapear)",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mapaindustrial.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Descobrir endereço/telefone e produto final (matéria-prima → produto)",
        "necessidade_identificada": "Validar linha de aço consumida",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Metalúrgica de porte relevante na cidade",
        "abordagem": "Primeiro entender o que fabricam; depois ofertar linha aderente.",
        "observacoes_comerciais": "Prioridade alta se confirmar transformação de bobina/chapa.",
    },
    {
        "empresa": "Ata Rodrifer Estruturas Metálicas",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis U; Tubo",
        "produto_secundario": "Chapa; Telha",
        "justificativa_produto": "FATO: listada em bases locais entre fabricantes de estruturas metálicas de Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Estruturas metálicas",
        "o_que_fabrica_constroi": "Estruturas metálicas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mestregeo listagens estruturas metálicas Araçatuba",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Localizar no Google Maps e qualificar",
        "necessidade_identificada": "Perfis/tubos para estruturas",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante de estruturas — compra aço para transformar",
        "abordagem": "Kit estrutura: metalon + perfil U + telha.",
        "observacoes_comerciais": "Lead B até confirmar porte.",
    },
    {
        "empresa": "Art Ferro Metalúrgica",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M15",
        "produto_provavel": "Chapa; Metalon — Provável — validar",
        "produto_secundario": "Barras; Tubo",
        "justificativa_produto": "FATO: listada entre metalúrgicas/estruturas de Araçatuba.",
        "potencial": "Baixo",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Metalúrgica",
        "o_que_fabrica_constroi": "Artefatos/estruturas — validar",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mestregeo listagens",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Não pesquisado",
        "proxima_acao": "Busca Maps + telefone",
        "necessidade_identificada": "Validar",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Nome sugere transformação de ferro/aço",
        "abordagem": "Qualificar antes de ofertar.",
        "observacoes_comerciais": "Lead não qualificado até responder perguntas 1–3.",
    },
    {
        "empresa": "Metalbens Estruturas Metálicas",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis; Tubo",
        "produto_secundario": "Chapa; Telha",
        "justificativa_produto": "FATO: listada como fabricação de estruturas metálicas em Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Estruturas metálicas",
        "o_que_fabrica_constroi": "Estruturas metálicas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mestregeo listagens",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Localizar e ligar",
        "necessidade_identificada": "Aço estrutural",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Transformador de aço em estruturas",
        "abordagem": "Oferta perfis + metalon.",
        "observacoes_comerciais": "",
    },
    {
        "empresa": "Sim Metálica",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis",
        "produto_secundario": "Chapa",
        "justificativa_produto": "FATO: listada entre fabricantes de estruturas metálicas em Araçatuba.",
        "potencial": "Baixo",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Estruturas metálicas",
        "o_que_fabrica_constroi": "Estruturas metálicas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mestregeo listagens",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Não pesquisado",
        "proxima_acao": "Busca Maps",
        "necessidade_identificada": "Validar",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Nome no segmento de estruturas",
        "abordagem": "Qualificar porte.",
        "observacoes_comerciais": "Lead não qualificado plenamente.",
    },
    {
        "empresa": "TZB Estruturas",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M2",
        "produto_provavel": "Metalon; Perfis U",
        "produto_secundario": "Tubo; Chapa",
        "justificativa_produto": "FATO: listada entre fabricantes de estruturas metálicas em Araçatuba.",
        "potencial": "Médio",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Estruturas metálicas",
        "o_que_fabrica_constroi": "Estruturas",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mestregeo listagens",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Localizar contato",
        "necessidade_identificada": "Aço estrutural",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Fabricante de estruturas",
        "abordagem": "Qualificar e ofertar perfis.",
        "observacoes_comerciais": "",
    },
    {
        "empresa": "Serralheria Criativa — Portas de Enrolar",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "M",
        "subcategoria": "M6",
        "produto_provavel": "Perfis / Barras / Kits portas de enrolar — VALIDAR NO CATÁLOGO",
        "produto_secundario": "Tubo 5\"; Metalon; Chapa",
        "justificativa_produto": "FATO: listada em guias locais como fabricação e manutenção de portas de enrolar automáticas e mecânicas.",
        "potencial": "Médio",
        "multiproduto": "Sim",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "tipo_operacao": "Fabricação de portas de enrolar",
        "o_que_fabrica_constroi": "Portas de enrolar e portões",
        "obras_atuais": "Não identificado",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "guiafix.com.br serralheiros Araçatuba",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Localizar telefone; ofertar linha portas de enrolar",
        "necessidade_identificada": "Matéria-prima para portas de enrolar",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Aderência direta à linha Portas de Enrolar",
        "abordagem": "Mesma da 5 Estrelas: kit porta de enrolar.",
        "observacoes_comerciais": "Comparar volume com Serralheria 5 Estrelas.",
    },
    {
        "empresa": "Obra — DECK 330 (TARRAF)",
        "cnpj": "N/A — obra",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "C",
        "subcategoria": "C4",
        "produto_provavel": "CA-50; Treliças; Telas",
        "produto_secundario": "Arame recozido",
        "justificativa_produto": "FATO: empreendimento residencial TARRAF em Araçatuba com incorporação registrada; consome armadura conforme estágio estrutural.",
        "potencial": "Alto",
        "multiproduto": "Não",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim (durante obra)",
        "tipo_operacao": "Canteiro residencial vertical",
        "o_que_fabrica_constroi": "Apartamentos DECK 330",
        "obras_atuais": "DECK 330 — TARRAF",
        "fornecedor_atual": "Não identificado — investigar canteiro",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Via TARRAF (17) 4004-6655",
        "whatsapp": "Não identificado",
        "email": "contato@tarraf.com.br",
        "site": "https://tarraf.com.br/empreendimentos/deck-330",
        "endereco": "Araçatuba/SP (consultar memorial/stand TARRAF)",
        "fonte": "tarraf.com.br",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Lead qualificado",
        "proxima_acao": "Visitar canteiro/stand; identificar estágio e fornecedor de aço",
        "necessidade_identificada": "Armadura da obra",
        "classificacao_comercial": "PROSPECT",
        "motivo_prospect": "Obra vertical ativa/recente da maior incorporadora na cidade",
        "abordagem": "Investigação de canteiro → CD oculta.",
        "observacoes_comerciais": "Validar se estrutura já foi concluída antes de priorizar.",
    },
    {
        "empresa": "Empreiteiras / CDs ocultas das obras Pacaembu e TARRAF",
        "cnpj": "Não identificado",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "CD",
        "subcategoria": "CD5",
        "produto_provavel": "CA-50; CA-60; Treliças; Telas",
        "produto_secundario": "Arame recozido; Fio-máquina",
        "justificativa_produto": "INFERÊNCIA: grandes obras habitacionais e verticais tipicamente contratam CD regional. Medida Exata e Serv Aço são candidatos; pode haver outras. Lead-placeholder para inteligência de canteiro.",
        "potencial": "Alto",
        "multiproduto": "Sim",
        "multioportunidade": "Sim",
        "consumo_estimado": "Alto",
        "compra_recorrente": "Sim",
        "tipo_operacao": "Corte e dobra atendendo grandes construtoras",
        "o_que_fabrica_constroi": "Armaduras para obras Pacaembu/TARRAF/Ferreira",
        "obras_atuais": "Campo Belo; Vida Nova 3; DECK 330; Brasília Square; Hub Ferreira",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "N/A",
        "endereco": "A descobrir via canteiros",
        "fonte": "Metodologia do projeto — investigação de obras",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Não pesquisado",
        "proxima_acao": "Em cada canteiro: anotar placa/fornecedor de aço; cruzar com Medida Exata/Serv Aço/Vivafer",
        "necessidade_identificada": "Quem fornece o aço das grandes obras",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Cliente oculto de maior valor potencial no funil construção",
        "abordagem": "Inteligência de campo, não cold call genérico.",
        "observacoes_comerciais": "Registro metodológico. Substituir por empresa real assim que identificada.",
    },
    {
        "empresa": "APC do Brasil (unidade Araçatuba)",
        "cnpj": "04.310.390/0004-08",
        "cidade": "Araçatuba",
        "estado": "SP",
        "distancia_km_aracatuba": "0",
        "categoria": "I",
        "subcategoria": "I15",
        "produto_provavel": "Inox / chapas — Provável baixo — validar se processo exige",
        "produto_secundario": "Não presumir inox sem validação",
        "justificativa_produto": "FATO: indústria de preparação de subprodutos do abate (capital alto). Contato com ambiente agroindustrial — inox só se houver linha sanitária. NÃO presumir compra de inox.",
        "potencial": "Baixo",
        "multiproduto": "Não",
        "multioportunidade": "Não",
        "consumo_estimado": "Baixo",
        "compra_recorrente": "Desconhecido",
        "tipo_operacao": "Subprodutos do abate",
        "o_que_fabrica_constroi": "Subprodutos animais",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Araçatuba/SP",
        "fonte": "mapaindustrial.com.br alimentos Araçatuba",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "situacao": "Pesquisado",
        "proxima_acao": "Só avançar se houver evidência de linha com inox/caldeiraria",
        "necessidade_identificada": "Sem justificativa clara de inox ainda",
        "classificacao_comercial": "INDEFINIDO",
        "motivo_prospect": "Indústria agro — possível mas não comprovado consumo de inox",
        "abordagem": "Não ofertar inox sem validação. Lead não qualificado para I até haver justificativa.",
        "observacoes_comerciais": "Incluído para não ignorar; classificação cautelosa conforme regras.",
    },
]

def main():
    out = Path(__file__).parent / "LEADS.csv"
    rows = []
    for i, lead in enumerate(LEADS, start=1):
        row = {"id": f"ARA-{i:03d}", **lead}
        rows.append(row)
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADERS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {len(rows)} leads → {out}")

    # Contagens
    from collections import Counter
    cat = Counter(r["categoria"] for r in rows)
    pot = Counter(r["potencial"] for r in rows)
    cls = Counter(r["classificacao_comercial"] for r in rows)
    print("Por categoria:", dict(cat))
    print("Por potencial:", dict(pot))
    print("Por classificação:", dict(cls))

if __name__ == "__main__":
    main()
