"""Leads — onda indicação Paulo (xlsx 22/09/2026)."""

DATA = "22/09/2026"

def _lead(**kwargs):
    base = {
        "cnpj": "Não identificado",
        "estado": "SP",
        "subcategoria": "",
        "produto_secundario": "Não identificado",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Não identificado",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Não identificado",
        "fonte": "Indicação Paulo (xlsx) — 22/09/2026",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "status": "Sem retorno",
        "proximo_contato": "",
        "ultima_compra": "",
        "crm": "Sem cadastro",
        "vendedor": "",
        "situacao": "Qualificado",
        "indicacao": "Paulo",
        "necessidade_identificada": "Validar se compra aço e quais bitolas/produtos",
    }
    base.update(kwargs)
    return base

LEADS_PAULO = [
    _lead(
        empresa="Metalpama",
        cnpj="46.151.478/0001-13",
        cidade="Birigui",
        estado="SP",
        distancia_km_aracatuba="20",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Birigui/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Valnei",
        crm="Sem compra",
        vendedor="",
        endereco="Birigui/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Birigui",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="ITB",
        cnpj="46.151.130/0001-26",
        cidade="Birigui",
        estado="SP",
        distancia_km_aracatuba="20",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Birigui/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Birigui/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Birigui",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Açomix",
        cnpj="21.969.045/0001-49",
        cidade="Birigui",
        estado="SP",
        distancia_km_aracatuba="20",
        categoria="Revenda",
        linha="Ferro para construção; Carbono",
        produto_provavel="CA-50 / vergalhão — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Birigui/SP. Classificação inicial Revenda / Ferro para construção; Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Toninho",
        crm="Inativo",
        vendedor="Hugo",
        endereco="Birigui/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Birigui",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Garcia",
        cnpj="13.704.423/0001-34",
        cidade="Andradina",
        estado="SP",
        distancia_km_aracatuba="100",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Andradina/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Inativo",
        vendedor="Sem informação",
        endereco="Andradina/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Andradina",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Carderoli",
        cnpj="64.175.631/0001-24",
        cidade="Coroados",
        estado="SP",
        distancia_km_aracatuba="55",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Coroados/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Coroados/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Coroados",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="F & L Cortes",
        cnpj="51.342.016/0001-13",
        cidade="Araçatuba",
        estado="SP",
        distancia_km_aracatuba="0",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Araçatuba/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Araçatuba/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Araçatuba",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Laticínio Vale do Pardo",
        cnpj="02.749.513/0001-25",
        cidade="Bataguassu",
        estado="MS",
        distancia_km_aracatuba="200",
        categoria="Indústria",
        linha="Inox",
        produto_provavel="Chapa inox / tubulação — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Bataguassu/MS. Classificação inicial Indústria / Inox por nome/setor — validar no contato.",
        potencial="Alto",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Bataguassu/MS",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Bataguassu",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="JVN",
        cnpj="22.354.167/0001-93",
        cidade="Três Lagoas",
        estado="MS",
        distancia_km_aracatuba="165",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Três Lagoas/MS. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Inativo",
        vendedor="Paulo Lettiere",
        endereco="Três Lagoas/MS",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Três Lagoas",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="GeneSeas",
        cnpj="04.459.073/0001-05",
        cidade="Aparecida do Taboado",
        estado="MS",
        distancia_km_aracatuba="180",
        categoria="Indústria",
        linha="Inox",
        produto_provavel="Chapa inox / tubulação — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Aparecida do Taboado/MS. Classificação inicial Indústria / Inox por nome/setor — validar no contato.",
        potencial="Alto",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Aparecida do Taboado/MS",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Aparecida do Taboado",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Veanholi",
        cnpj="Não identificado",
        cidade="Guararapes",
        estado="SP",
        distancia_km_aracatuba="55",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Guararapes/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Inativo",
        vendedor="",
        endereco="Guararapes/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Guararapes",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Sanches e Aquino",
        cnpj="10.909.325/0001-45",
        cidade="Pauliceia",
        estado="SP",
        distancia_km_aracatuba="130",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Pauliceia/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem compra",
        vendedor="",
        endereco="Pauliceia/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Pauliceia",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Irbi",
        cnpj="05.317.917/0001-38",
        cidade="Araçatuba",
        estado="SP",
        distancia_km_aracatuba="0",
        categoria="Indústria",
        linha="Carbono; Inox",
        produto_provavel="Chapa inox / tubulação — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Araçatuba/SP. Classificação inicial Indústria / Carbono; Inox por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem compra",
        vendedor="",
        endereco="Araçatuba/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Araçatuba",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Momesso",
        cnpj="48.712.319/0001-76",
        cidade="Birigui",
        estado="SP",
        distancia_km_aracatuba="20",
        categoria="Metalúrgica",
        linha="Carbono",
        produto_provavel="Chapa / tubo / perfis — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Birigui/SP. Classificação inicial Metalúrgica / Carbono por nome/setor — validar no contato.",
        potencial="Médio",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Birigui/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Birigui",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
    _lead(
        empresa="Usina Caeté",
        cnpj="12.282.034/0017-62",
        cidade="Pauliceia",
        estado="SP",
        distancia_km_aracatuba="130",
        categoria="Indústria",
        linha="Carbono; Inox",
        produto_provavel="Chapa inox / tubulação — Provável — validar",
        produto_secundario="Não identificado",
        justificativa_produto="Indicação Paulo. Empresa em Pauliceia/SP. Classificação inicial Indústria / Carbono; Inox por nome/setor — validar no contato.",
        potencial="Alto",
        multioportunidade="Não",
        consumo_estimado="Médio",
        compra_recorrente="Provável — validar",
        tipo_operacao="Não identificado — validar",
        o_que_fabrica_constroi="Não identificado — validar",
        comprador="Não identificado",
        crm="Sem cadastro",
        vendedor="",
        endereco="Pauliceia/SP",
        fonte="Indicação Paulo (xlsx) — 22/09/2026",
        proxima_acao="Qualificar porte, comprador e volume; validar linha de aço.",
        necessidade_identificada="Validar se compra aço e quais bitolas/produtos",
        motivo_prospect="Indicação Paulo — Pauliceia",
        abordagem="Abrir pelo contato indicado (se houver); senão telefone/CNPJ público.",
        observacoes_comerciais="Importado do xlsx Paulo. Campos de produto/consumo inferidos com cautela — validar.",
        indicacao="Paulo",
    ),
]
