"""Leads — onda setores: pré-moldados, artefatos, fundações, infraestrutura, silos, tanques."""

DATA = "22/09/2026"

def _lead(**kwargs):
    base = {
        "cnpj": "Não identificado",
        "estado": "SP",
        "subcategoria": "",
        "produto_secundario": "Não identificado",
        "multioportunidade": "Não",
        "consumo_estimado": "Médio",
        "compra_recorrente": "Provável — validar",
        "obras_atuais": "N/A",
        "fornecedor_atual": "Não identificado",
        "comprador": "Não identificado",
        "cargo_comprador": "Provável — compras/produção; validar",
        "telefone": "Não identificado",
        "whatsapp": "Não identificado",
        "email": "Não identificado",
        "site": "Não identificado",
        "endereco": "Não identificado",
        "data_pesquisa": DATA,
        "ultimo_contato": "",
        "status": "Sem retorno",
        "proximo_contato": "",
        "ultima_compra": "",
        "situacao": "Qualificado",
        "necessidade_identificada": "Validar volume e bitolas",
    }
    base.update(kwargs)
    return base


LEADS_SETORES = [
    # --- Pré-moldados ---
    _lead(
        empresa="Pré-Moldados Panorama",
        cnpj="55.296.545/0001-89",
        cidade="Panorama",
        distancia_km_aracatuba="200",
        categoria="Pré-moldados",
        produto_provavel="CA-50 / vergalhão (armadura para pré-moldados e protendido)",
        produto_secundario="Treliças; Telas; Arame; Aços para protensão — Provável — validar",
        justificativa_produto="FATO: fábrica de estruturas pré-moldadas de concreto armado/protendido desde ~1979; parque industrial ~67.000 m²; atende obras industriais/comerciais/agro em todo o país a partir de Panorama/SP (borda do raio 200 km).",
        potencial="Alto",
        multioportunidade="Sim",
        consumo_estimado="Alto",
        compra_recorrente="Sim",
        tipo_operacao="Fabricação de pré-moldados de concreto armado e protendido",
        o_que_fabrica_constroi="Galpões, pilares, vigas e estruturas pré-moldadas",
        telefone="(18) 3871-3000",
        email="contato@premoldadospanorama.com.br",
        site="https://www.premoldadospanorama.com.br/",
        endereco="Rod. SP-294 (Cmte. João Ribeiro de Barros), Km 684 — Panorama/SP — CEP 17980-000",
        fonte="premoldadospanorama.com.br; quemfornece; econodata CNPJ 55.296.545/0001-89",
        proxima_acao="Ligar comercial: volume mensal de CA-50/protendido e fornecedor atual",
        necessidade_identificada="Vergalhão e aço para armadura/protensão em série de fábrica",
        motivo_prospect="Grande fábrica de pré-moldados na borda do raio (~200 km) — consumo contínuo de armadura",
        abordagem="Oferta CA-50/60 + logística Panorama. Perguntar se compram direto de usina ou via CD/distribuidor.",
        observacoes_comerciais="Alta prioridade do eixo pré-moldados. Validar se protensão usa cordoalha própria ou compra terceira.",
    ),
    _lead(
        empresa="Protendit — Pré-fabricados e Fundações (unidade SJRP)",
        cnpj="61.196.390/0002-92 (filial SJRP)",
        cidade="São José do Rio Preto",
        distancia_km_aracatuba="135",
        categoria="Pré-moldados",
        produto_provavel="CA-50 / aço para pré-fabricados e estacas",
        produto_secundario="Lajes; Vigas; Pilares; Estacas pré-fabricadas",
        justificativa_produto="FATO: referência nacional em pré-fabricados e estacas desde 1958; fábrica em SJRP (Rua José Guidi) com capacidade publicada na ordem de milhares de m³/mês; também executa fundações.",
        potencial="Alto",
        multioportunidade="Sim",
        consumo_estimado="Alto",
        compra_recorrente="Sim",
        tipo_operacao="Pré-fabricados de concreto + fundações (estacas)",
        o_que_fabrica_constroi="Estacas, vigas, lajes, painéis, pilares, coberturas pré-fabricadas",
        telefone="(17) 3214-7200 / (17) 3600-0505",
        email="sjp@protendit.com.br",
        site="https://protendit.com.br/",
        endereco="Rua José Guidi, 341 — Distrito Industrial — São José do Rio Preto/SP — CEP 15035-500",
        fonte="protendit.com.br/contato; mestregeo CNPJ filial; LinkedIn Protendit",
        proxima_acao="E-mail/ligar sjp@: mapear compra de vergalhão vs aço de protensão; volume mensal",
        necessidade_identificada="Aço para pré-fabricados e estacas em escala industrial",
        motivo_prospect="Maior player de pré-fabricado/estacas no polo SJRP (~135 km)",
        abordagem="Abordar compras da fábrica SJRP (não só canteiro). Oferta CA-50 + bitolas de estaca.",
        observacoes_comerciais="⭐ MULTIOPORTUNIDADE (pré-moldados + fundações). Matriz/comercial SP também existe — priorizar unidade SJRP.",
    ),
    _lead(
        empresa="Concrerio Pré-Moldados de Concreto",
        cnpj="51.836.427/0001-65",
        cidade="São José do Rio Preto",
        distancia_km_aracatuba="135",
        categoria="Pré-moldados",
        produto_provavel="CA-50 / armadura para pré-moldados — Provável — validar",
        produto_secundario="Treliças; Telas — Provável — validar",
        justificativa_produto="FATO: CNPJ ativo desde 1979; CNAE fabricação de estruturas pré-moldadas de concreto armado; sede no Distrito Industrial de SJRP (mesmo eixo da Protendit).",
        potencial="Médio",
        consumo_estimado="Médio",
        tipo_operacao="Fabricação de pré-moldados de concreto armado",
        o_que_fabrica_constroi="Estruturas pré-moldadas de concreto armado (série/encomenda)",
        endereco="Rua José Guidi, s/n — Distrito Industrial — São José do Rio Preto/SP — CEP 15035-500",
        fonte="guiapj CNPJ 51.836.427/0001-65; diariocidade filial 0002-46",
        proxima_acao="Visita/Maps DI SJRP: localizar telefone e porte; validar se ainda opera em escala",
        necessidade_identificada="Armadura para linha de pré-moldados",
        motivo_prospect="Pré-moldados históricos no DI de SJRP — completar cluster com Protendit",
        abordagem="Qualificar volume antes de cotação. Se ME/baixa produção, baixar potencial.",
        observacoes_comerciais="Telefone público não localizado na pesquisa — priorizar visita presencial no DI.",
    ),
    # --- Artefatos de concreto ---
    _lead(
        empresa="Lajes Bandeirantes Araçatuba Artefatos de Concretos",
        cidade="Araçatuba",
        distancia_km_aracatuba="0",
        categoria="Artefatos de concreto",
        produto_provavel="CA-50 / treliças para lajes — Provável — validar",
        produto_secundario="Telas; Arame — Provável — validar",
        justificativa_produto="FATO: listada em Araçatuba como lajes/artefatos de concreto e pré-moldados; telefone público local.",
        potencial="Médio",
        tipo_operacao="Fabricação/comércio de lajes e artefatos de concreto",
        o_que_fabrica_constroi="Lajes e artefatos de concreto",
        telefone="(18) 3621-6864",
        endereco="Rua Gonçalves Ledo, 750 — São Joaquim — Araçatuba/SP — CEP 16050-300",
        fonte="solutudo Lajes Bandeirantes Araçatuba; planetabrasileiro",
        proxima_acao="Ligar: confirmar se fabrica laje treliçada e volume de aço/mês",
        necessidade_identificada="Vergalhão/treliça para lajes",
        motivo_prospect="Artefato local em Araçatuba — rota fácil e consumo de armadura de laje",
        abordagem="Oferta treliças H8/H12 + CA-50. Validar se é fábrica ou só revenda/montagem.",
        observacoes_comerciais="Qualificar porte: se só monta laje com aço de terceiros, comprador pode ser outro.",
    ),
    _lead(
        empresa="Rondon Cochos Araçatuba",
        cidade="Araçatuba",
        distancia_km_aracatuba="0",
        categoria="Artefatos de concreto",
        produto_provavel="CA-50 / ferragem para cochos e pré-moldados agro — Provável — validar",
        produto_secundario="Arame; Estribos — Provável — validar",
        justificativa_produto="FATO: fabricante local de artefatos de cimento/pré-moldados para agropecuária (cochos, pilares, mourões, tubos, aduelas); site/listagem cita ferragem estrivada no concreto ~30 MPa.",
        potencial="Médio",
        tipo_operacao="Pré-moldados/artefatos de concreto para agropecuária",
        o_que_fabrica_constroi="Cochos, bebedouros, pilares, mourões, tubos e aduelas",
        telefone="(18) 99748-7213 / (18) 99713-7881",
        whatsapp="(18) 99748-7213",
        email="rondoncochos@hotmail.com",
        endereco="Av. José Ferreira Batista, 3335 — Ipanema — Araçatuba/SP — CEP 16052-000",
        fonte="solutudo Rondon Cochos Araçatuba",
        proxima_acao="WhatsApp: volume de ferragem/mês e bitolas usadas nos cochos/pilares",
        necessidade_identificada="Ferragem para linha agro de pré-moldados",
        motivo_prospect="Artefato agro local com armadura explícita no produto",
        abordagem="Oferta CA-50/estribos em volumes de série. Ticket médio — validar recorrência.",
        observacoes_comerciais="Porte menor que Panorama/Protendit; útil na rota Araçatuba.",
    ),
    # --- Fundações ---
    _lead(
        empresa="Profund — Engenharia e Fundações Especiais",
        cidade="São José do Rio Preto",
        distancia_km_aracatuba="135",
        categoria="Fundações",
        produto_provavel="CA-50 / armadura para estacas e paredes diafragma — Provável — validar",
        produto_secundario="Treliças; Barras — Provável — validar",
        justificativa_produto="FATO: empresa de SJRP (desde 2006) especializada em fundações especiais (hélice contínua, escavadas, raiz, diafragma) e locação de perfuratrizes — consumo típico de armadura por obra.",
        potencial="Alto",
        multioportunidade="Sim",
        consumo_estimado="Alto",
        compra_recorrente="Sim (por obra)",
        tipo_operacao="Execução de fundações especiais",
        o_que_fabrica_constroi="Estacas hélice/escavadas/raiz, paredes diafragma, provas de carga",
        telefone="(17) 98193-1884",
        whatsapp="(17) 98193-1884",
        email="comercial@profundfundacoes.com.br",
        site="https://profundfundacoes.com.br/",
        endereco="Rua Ipiranga, 4137 — Sala 04 — Santos Dumont — São José do Rio Preto/SP — CEP 15020-040",
        fonte="profundfundacoes.com.br",
        proxima_acao="WhatsApp comercial: quem fornece a armadura das estacas; volume médio/obra",
        necessidade_identificada="Armadura para fundações profundas por obra",
        motivo_prospect="Fundações especiais em SJRP — comprador recorrente por canteiro",
        abordagem="Mapear se arma no pátio próprio ou compra kit pronto de CD. Oferta CA-50 + logística de obra.",
        observacoes_comerciais="Consumo por obra (não fábrica contínua). Cruzar com pipeline TARRAF/Pacaembu na região.",
    ),
    _lead(
        empresa="Master Bauru Engenharia e Fundações",
        cidade="Bauru",
        distancia_km_aracatuba="190",
        categoria="Fundações",
        produto_provavel="CA-50 / armadura para estacas e tubulões — Provável — validar",
        produto_secundario="Barras; Estribos — Provável — validar",
        justificativa_produto="FATO: +30 anos em fundações (hélice contínua, escavadas, tubulões); sede Bauru; atende residencial/comercial/industrial e infraestrutura.",
        potencial="Alto",
        consumo_estimado="Alto",
        compra_recorrente="Sim (por obra)",
        tipo_operacao="Execução de fundações",
        o_que_fabrica_constroi="Tubulões, estacas escavadas e hélice contínua monitorada",
        telefone="(14) 3203-5163",
        whatsapp="(14) 99778-7651",
        email="contato@masterbauru.com.br",
        site="https://www.masterbauru.com.br/",
        endereco="Rua Dimas Simonetti, 2-59 — Lot. Mário Luiz Rodrigues do Prado — Bauru/SP — CEP 17023-875",
        fonte="masterbauru.com.br",
        proxima_acao="WhatsApp/e-mail: volume de armadura por obra e fornecedor atual",
        necessidade_identificada="Armadura para fundações",
        motivo_prospect="Fundações de porte em Bauru (~190 km) — borda do raio com contato público",
        abordagem="Oferta CA-50 para kits de estaca. Avaliar frete vs fornecedor local de Bauru.",
        observacoes_comerciais="Agrupar rota Bauru com CPA (já na base).",
    ),
    # --- Infraestrutura ---
    _lead(
        empresa="COPEL Construções — Tubos Copel",
        cnpj="00.623.468/0001-32",
        cidade="Araçatuba",
        distancia_km_aracatuba="0",
        categoria="Infraestrutura",
        produto_provavel="CA-50 / armadura para tubos, aduelas e pré-moldados de drenagem",
        produto_secundario="Telas; Arame — Provável — validar",
        justificativa_produto="FATO: indústria local (+50 anos) de pré-moldados para drenagem/saneamento (tubos, aduelas, ovóides, reservatórios) e construtora de obras de arte de infraestrutura; concreto usinado próprio.",
        potencial="Alto",
        multioportunidade="Sim",
        consumo_estimado="Alto",
        compra_recorrente="Sim",
        tipo_operacao="Fabricação de artefatos/pré-moldados + obras de infraestrutura",
        o_que_fabrica_constroi="Tubos, aduelas, ovóides, reservatórios de detenção; galerias, pontes, canais",
        obras_atuais="Obras de drenagem/infraestrutura em SP e estados vizinhos — validar pipeline",
        telefone="(18) 3636-7200",
        email="vendas@tuboscopel.com.br",
        site="https://tuboscopel.com.br/",
        endereco="Rod. Marechal Rondon, Km 540 — Araçatuba/SP — CEP 16027-231",
        fonte="tuboscopel.com.br; guiapj CNPJ 00.623.468/0001-32",
        proxima_acao="Ligar vendas@: volume mensal de armadura na fábrica + se compram para obras próprias",
        necessidade_identificada="Armadura contínua para linha de tubos/aduelas e obras",
        motivo_prospect="Âncora local de infraestrutura/pré-moldado de drenagem em Araçatuba",
        abordagem="Abrir pela fábrica (consumo recorrente). Depois mapear aço das obras de arte.",
        observacoes_comerciais="⭐ MULTIOPORTUNIDADE (fábrica + infraestrutura). Não confundir com a utility Copel/PR.",
    ),
    # --- Silos e estruturas agro ---
    _lead(
        empresa="Mardel Industrial",
        cidade="Presidente Prudente",
        distancia_km_aracatuba="145",
        categoria="Silos e estruturas agro",
        produto_provavel="Chapa aço carbono; Bobina",
        produto_secundario="Tubos; Perfis; Chapas para tanques/reservatórios",
        justificativa_produto="FATO: desde 1978 em Prudente; fabrica silos metálicos, estruturas, reservatórios/tanques, corte/dobra/calandragem de chapas e montagem industrial.",
        potencial="Alto",
        multioportunidade="Sim",
        consumo_estimado="Alto",
        compra_recorrente="Sim",
        tipo_operacao="Fabricação de silos, estruturas e reservatórios metálicos + caldeiraria",
        o_que_fabrica_constroi="Silos de grãos, estruturas metálicas, tanques/reservatórios, peças calandradas",
        telefone="(18) 3222-7621 / (18) 3222-7221",
        whatsapp="(18) 98116-6648",
        email="adrianomardel@hotmail.com / markinmardel@hotmail.com",
        site="https://mardelindustrial.com.br/",
        endereco="Av. José Moisés Ferreira, 705 — Presidente Prudente/SP — CEP 19043-120",
        fonte="mardelindustrial.com.br (silos/contato/sobre)",
        proxima_acao="Ligar/WhatsApp Adriano: espessuras de chapa para silos/tanques e volume mensal",
        necessidade_identificada="Chapas/bobinas para silos, tanques e estruturas agroindustriais",
        motivo_prospect="Fabricante agro/metalúrgico consolidado no polo Prudente (~145 km)",
        abordagem="Oferta chapa carbono para silo/tanque; perguntar mix galvanizado vs preto.",
        observacoes_comerciais="⭐ MULTIOPORTUNIDADE (silos + tanques + estruturas). Rota Prudente com usinas/caldeirarias já na base.",
    ),
    # --- Tanques e vasos ---
    _lead(
        empresa="Metalúrgica Canaã — Reservatórios",
        cidade="Araçatuba",
        distancia_km_aracatuba="0",
        categoria="Tanques e vasos",
        produto_provavel="Chapa aço carbono (reservatórios metálicos)",
        produto_secundario="Bobina; Perfurações/acessórios — Provável — validar",
        justificativa_produto="FATO: fabricante local (+20 anos) de reservatórios metálicos em Araçatuba; endereço e WhatsApp públicos no site.",
        potencial="Médio",
        consumo_estimado="Médio",
        tipo_operacao="Fabricação de reservatórios metálicos",
        o_que_fabrica_constroi="Reservatórios metálicos (água e afins)",
        telefone="(18) 99825-9292",
        whatsapp="(18) 99825-9292",
        email="reservatorioscanaa@gmail.com",
        site="https://metalurgicacanaa.com.br/",
        endereco="Rod. Marechal Rondon, Km 534 — Guanabara — Araçatuba/SP — CEP 16026-005",
        fonte="metalurgicacanaa.com.br",
        proxima_acao="WhatsApp: espessuras e volume mensal de chapa; fornecedor atual",
        necessidade_identificada="Chapa carbono para reservatórios",
        motivo_prospect="Tanques/reservatórios fabricados em Araçatuba — compra local de chapa",
        abordagem="Oferta chapa carbono sob medida. Validar se atende também combustível/industrial.",
        observacoes_comerciais="Porte médio. Complementar a Passador (caldeiraria pesada Andradina).",
    ),
    _lead(
        empresa="Mundial Reservatórios Metálicos",
        cnpj="33.706.963/0001-64",
        cidade="Birigui",
        distancia_km_aracatuba="20",
        categoria="Tanques e vasos",
        produto_provavel="Chapa aço carbono (tanques e reservatórios)",
        produto_secundario="Não identificado",
        justificativa_produto="FATO: CNPJ ativo em Birigui com CNAE fabricação de tanques/reservatórios metálicos; telefone público em bases cadastrais.",
        potencial="Médio",
        tipo_operacao="Fabricação de tanques e reservatórios metálicos",
        o_que_fabrica_constroi="Tanques e reservatórios metálicos",
        telefone="(18) 3641-1868",
        endereco="Rua Manoel Segundo Celice — Residencial Prado — Birigui/SP — CEP 16201-263",
        fonte="guiadocnpj Mundial Reservatórios Metálicos Birigui CNPJ 33.706.963/0001-64",
        proxima_acao="Ligar: confirmar operação ativa, espessuras e volume de chapa",
        necessidade_identificada="Chapa para tanques/reservatórios",
        motivo_prospect="Fabricante de tanques a 20 km — rota Birigui",
        abordagem="Qualificar porte e mix (água vs combustível). Oferta chapa carbono.",
        observacoes_comerciais="Validar se ainda produz em escala (EIRELI). Agrupar visita com Serv Aço/Saita.",
    ),
]
